### ISSUE TITLE
Identify routes for User and Organization

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc-app#178]
I'm still debating whether we want to adopt the route format `{organization}/{challenge}`. If we take this option, it means that ideally we want `/{user}` and `/{organization}` to cohabitate. I have an idea how to achieve that so it's not an issue.

My question is regarding what an "organization" is and whether we distinguish between generic organizations (Sage Bionetworks, IBM, etc.) and "challenge organizations" (e.g. DREAM, CAMI, precisionFDA). If we follow the GitHub model up to the end, any organization - and even user - would be able to register a challenge in the ROCC. Is that what we want? If yes and a challenge is organized by DREAM in collaboration with N organizations (e.g. IBM, UW, etc.), does it sound natural that the challenge would be hosted under `dream/awesome-challenge` rather than `ibm/awesome-challenge` or `foo/awesome-challenge`? I think that this may be OK. IBM would still have an "organization space" available at `ibm/` where "activity updates" could include notifications about the awesome-challenge because the ROCC would know that IBM is one of the organization behind the awesome-challenge.

## Proposal

- We support user and organization routes and they coexist.
- Any user and organization can register a challenge that will be hosted in their user/org space. Example
  - `awesome-user/awesome-challenge`
  - `awesome-org/another-awesome-challenge`
- Challenge names would be unique inside a user/org space, providing organizers with more options to name their challenge how they want. For example, the following challenges could exist.
  - `ibm/digital-mammography-challenge`
  - `tschaffter/digital-mammography-challenge`

**Comment by rrchai** [comment]
I like your proposal that both user and organization are able to create their own challenges.  

>My question is regarding what an "organization" is and whether we distinguish between generic organizations (Sage Bionetworks, IBM, etc.) and "challenge organizations" (e.g. DREAM, CAMI, precisionFDA).

I would say yes and no. Having a "challenge organizations" would be helpful to define where the challenge should be hosted when there are multiple organizations involved and collaborated. However, I am thinking what if a challenge (like `BraTs`) involve multiple "platform/challenge organizations". Does it mean we still need to consider which organization we should host the challenge?

>IBM would still have an "organization space" available at ibm/ where "activity updates" could include notifications about the awesome-challenge because the ROCC would know that IBM is one of the organization behind the awesome-challenge.

I like the notification method you mentioned. Based on your proposal, can we just let organization decide who should register the challenge in the ROCC and we host the challenge whichever organization register first and the rest of organization will the notifications.

For example, IBM, Sage Bionetworks and UW will collaborate and register an `awesome-challenge` in the ROCC. Somehow, Sage Bionetworks register before the other two organizations and the challenge is hosted in the `sage-bionetworks/awesome-challenge`. IBM and UW will get notifications since they are the collaborators, but they cannot register the same challenge again as an organization. (individual users can still register `awesome-challenge`).

**Comment by tschaffter** [comment]
> However, I am thinking what if a challenge (like BraTs) involve multiple "platform/challenge organizations".

@rrchai To clarify, challenge organizations and challenge platforms are different things. This is motivated by the fact that a challenge organization does not necessarily have a challenge platform (e.g. a user may want to organize a challenge but does not have a dedicated challenge platform). A challenge platform is just a property of a challenge and not used to determine "where" a challenge in located in the ROCC.

About the `BraTs` use case mentioned. For simplicity, I would limit ourselves to the case where a challenge is associated to one challenge platform. Therefore BraTS would need to create two challenges in the ROCC, for example:

- `miccai/brats-challenge-2021-kaggle` with `Challenge.platform = 'kaggle'` and `Challenge.organizations` that is a list that does not include `Sage Bionetworks`.
- `miccai/brats-challenge-2021-synapse` with `Challenge.platform = 'synapse'` and `Challenge.organizations` that is a list that does include `Sage Bionetworks`.

I didn't consider the challenge platform as part of my proposal but hopefully the above clarification makes sense.

> I like the notification method you mentioned. Based on your proposal, can we just let organization decide who should register the challenge in the ROCC and we host the challenge whichever organization register first and the rest of organization will the notifications.

Yes! Typically the main challenge organization would step up and indicates clearly that the challenge will be organized under its space. For example, DREAM would notify that the organizations involved in the organization of a challenge that all DREAM challenges must be located and managed under `dream/{challenge}`.

> IBM and UW will get notifications since they are the collaborators, but they cannot register the same challenge again as an organization.

Technically if there is a challenge `dream/awesome-challenge`, IBM could create a challenge named `ibm/awesome-challenge`. Technically the ROCC won't prevent that but the two challenges will be considered as two different things. Ideally Sage Bionetworks and IBM will identify whether the challenge should be registered under `sage-bionetworks/` or `ibm/`. Anyway the challenge is going to include both `Sage Bionetworks` and `IBM` in `Challenge.organizations`.
